<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="36223" started-at="2018-02-28T07:28:00Z" finished-at="2018-02-28T07:28:37Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="36223" started-at="2018-02-28T07:28:00Z" finished-at="2018-02-28T07:28:37Z">
      <class name="com.mercury.Testcases.MainPageTests">
        <test-method status="FAIL" signature="_doContact()[pri:0, instance:com.mercury.Testcases.MainPageTests@6043cd28]" name="_doContact" duration-ms="13" started-at="2018-02-28T07:28:00Z" finished-at="2018-02-28T07:28:00Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.mercury.Testcases.MainPageTests._doContact(MainPageTests.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- _doContact -->
        <test-method status="PASS" signature="_doLogin()[pri:0, instance:com.mercury.Testcases.MainPageTests@6043cd28]" name="_doLogin" duration-ms="36171" started-at="2018-02-28T07:28:00Z" finished-at="2018-02-28T07:28:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- _doLogin -->
        <test-method status="PASS" signature="_doResgiter()[pri:0, instance:com.mercury.Testcases.MainPageTests@6043cd28]" name="_doResgiter" duration-ms="9" started-at="2018-02-28T07:28:37Z" finished-at="2018-02-28T07:28:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- _doResgiter -->
        <test-method status="PASS" signature="_doSupport()[pri:0, instance:com.mercury.Testcases.MainPageTests@6043cd28]" name="_doSupport" duration-ms="0" started-at="2018-02-28T07:28:37Z" finished-at="2018-02-28T07:28:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- _doSupport -->
      </class> <!-- com.mercury.Testcases.MainPageTests -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
